### ISSUE TITLE
[BUG] After loading a database and adding new properties, new data cannot be added

### ISSUE THREAD

**Issue by radubolovan** [radubolovan/Godot-Database-Manager#1]
Steps to reproduce:
1) Load a database
2) Create new property
3) Edit data

OBS: data cannot be added to database/current table

**Comment by DCowboy** [comment]
I think this issue might affect creation of new databases too. After purging and re-installing for new update, I was able to:
1. Create new database
2. create new table
Was given no options to create any properties, much less add data. Here was the errors I was given for trying:
 modules/gdscript/gdscript.cpp:806 - Condition "err" is true. Returned: err
 Cannot load source code from file 'res://addons/godot_db_manager/db_table.gd'.
 Failed loading resource: res://addons/godot_db_manager/db_table.gd.
 res://addons/godot_db_manager/db_interface.gd:237 - Attempt to call function 'new' in base 'null instance' on a null instance.
 modules/gdscript/gdscript.cpp:806 - Condition "err" is true. Returned: err
 Cannot load source code from file 'res://addons/godot_db_manager/db_table.gd'.
 Failed loading resource: res://addons/godot_db_manager/db_table.gd.
 res://addons/godot_db_manager/db_interface.gd:237 - Attempt to call function 'new' in base 'null instance' on a null instance.
ERROR: database::on_select_table( 0 ) havinng 0 tables count

Is this the same issue? Or should I post it as a new one?

**Comment by radubolovan** [comment]
This should be fixed with commit "5b49da58208f51f5bcca5f50962f8a78d1d3e08e".
Please check again when you have the time and I'll look into it if the problem persists.

**Comment by DCowboy** [comment]
This issue seems to be sorted now. Not only could I create properties and add data to them and save them but could load them and add more.

**Comment by radubolovan** [comment]
I'm closing this now.
Thank you!
