### ISSUE TITLE
[IMPROVEMENT] Docs + some explanations

### ISSUE THREAD

**Issue by nonunknown** [radubolovan/Godot-Database-Manager#2]
Hi, I really liked this plugin, very useful. But how I'm supposed to retrieve data? 

* In the example file, you saved ["Gold","Silver","Bronze"] So how the best way to retrieve...
* It is possible to filter data? like: [[GOLD,0],[GOLD,1]] -> where ID > 0 -> [[GOLD,1]]
 
And I want to know if you can tell me why did you choose using default IDS for table properties instead of default ID for table data?

**Comment by radubolovan** [comment]
Hello,
Thank you for your requests !
I added more examples for 2.0 here: https://github.com/radubolovan/Godot-Database-Manager/blob/2.0/prj/db_test.gd

Once I finish implementing 2.0, I'll add more examples and documentation.

I'm not sure I understand your last question though, can you give me an example please?

**Comment by nonunknown** [comment]
tkx for answering! Nice to know a 2.0 v

about the second question, did you know MongoDB or SQL? I was thinking about getting data

| METAL   | VALUE |
|---------|-------|
| GOLD    | 10    |
| BRONZE  | 5     |
| DIAMOND | 50    |

user type something like get_data("where","VALUE",">",7) returns:
`{"METAL":{"GOLD","DIAMOND"},"VALUE":{"10","50"}}`

**Comment by DCowboy** [comment]
@radubolovan, I believe he's talking about how for some reason you're giving properties Unique IDentifiers (1, 2 , 3, etc., when full-scale database software (like Access) usually gives that to the data itself:
UID (automatic) | gold (type - int) | helmet (res)
----------------------|---------------------|------------------
1 | 10 | res://helmet_a.tscn
2 |  25 | null



| UID (automatic)  | gold (type - int)  | helmet (res)  |
|---|---|---|
| 1 | 10 | res://helmet_a.tscn |
| 2 |  25 | null |

Apparently, before coffee I can't even understand markdown enough to make tables properly...lol Hopefully it will work well enough to explain.

@nonunknown Thank you, that link helped me understand what I was doing wrong (and what Github's markdown explanation page, doesn't explain or show an example of properly.

**Comment by nonunknown** [comment]
> @radubolovan, I believe he's talking about how for some reason you're giving properties Unique IDentifiers (1, 2 , 3, etc., when full-scale database software (like Access) usually gives that to the data itself:
> UID (automatic) | gold (type - int) | helmet (res)
> ----------------------|---------------------|------------------
> 1 | 10 | res://helmet_a.tscn
> 2 | 25 | null
> 
> Apparently, before coffee I can't even understand markdown enough to make tables properly...lol Hopefully it will work well enough to explain.

you explained it perfectly tkx, btw I use this to make tables https://www.tablesgenerator.com/markdown_tables

**Comment by radubolovan** [comment]
@nonunknown, currently filtering is limited to "=" only. It's a good idea to add "<", ">", "<=", ">=" and "!=" though. Thank you !
Please see here an example: https://github.com/radubolovan/Godot-Database-Manager/blob/2.0/prj/db_test.gd
As for autogenerate unique identifiers, also a good idea.
I'll add these 2 features to the 2.0 plan.

**Comment by radubolovan** [comment]
And thank you @DCowboy for helping out.
I'll keep this one open for farther discutions.

**Comment by radubolovan** [comment]
Hello guys,
I finished implementing all of the backend functionalities for 2.0, but most of them need tests.
I'll make a few scripts in the next days / weeks that will automatically test these features, but if you want to jump in and help with the tests, please do it.
Interface also needs a lot of improvements.
Here is what I did so far:
https://github.com/radubolovan/Godot-Database-Manager/blob/2.0/prj/docs/2_0_todo.txt

**Comment by nonunknown** [comment]
wow amazing!!! I'll do some tests

**Comment by radubolovan** [comment]
I already added 3 stress test scripts and fix a few problems. Maybe will inspire you and hopefully you will see problems that I don't see. We need to find as many case scenarios as we can and test them.
Please pull and see the "tests" directory.

**Comment by nonunknown** [comment]
@radubolovan Okay I'm doing a plugin here, and I'll use GDM as data saving, maybe this create some scenerio to help improving yours
