### ISSUE TITLE
Minor publicity?

### ISSUE THREAD

**Issue by DCowboy** [radubolovan/Godot-Database-Manager#20]
Sorry I've been away awhile. Lots of things have been changing for me, not the least of which is that I've decided to leave fakebook completely, which is part of why I've been out of contact. That said, I have been kind of lurking keeping an eye on this project while I've been cycling through and breaking prototypes.

I've recently, as a distraction from all the distracting stuff going on, started a slow-posting blog about my project. Since we seem to have a good rapport, I figured I'd see what you thought about me mentioning this project in my blog with a link to it. The idea would be to give it exposure from a small group over at minds.com as well as whoever else happens to see it as a result of wandering onto my channel. 

I wouldn't expect there to be an issue. but, I wouldn't want to be wrong either, so I figured I'd get your thoughts.

**Comment by DCowboy** [comment]
Since I haven't heard anything in about twenty four hours, I guess I'll assume that you don't mind and that it's a non-issue. If it does turn out to be wrong, I suppose I can edit it. I was really hoping feedback first, but I promised interested people to get it done this weekend.

**Comment by radubolovan** [comment]
Hey there,

I've been busy with my other projects lately, so sorry for late answer.
I have nothing against any type of publicity about this project. Since this is a public Open Source project with M.I.T. license, you have the freedom to do about anything you want about it. Adding my name in there would be highly appreciated, but if you can't do it there's no problem about it.

I googled about your blog and didn't find anything. When you have the time, please provide me a full link to your blog about this so I can read it (here or send me an e-mail).

**Comment by DCowboy** [comment]
I'd be surprised if google did find it as it's still new,with only three posts so far and I don't think 100 people have read it yet. (That's the minor part...lol) So far, it's been confined to minds.com. 

But, here's a link to that particular blog post so you can see I did mention your name and gave a link to this project. [https://www.minds.com/newsfeed/1106400214752985088?referrer=tim_dc1a0](url)

**Comment by radubolovan** [comment]
Nice article and thank you !

**Comment by DCowboy** [comment]
No problem. Sorry it wasn't more than a mention. I was playing it cautious.

I metaphorically tripped over myself again not knowing how to plan the details, I'm thinking of taking what I've learned to a new prototype and see how much farther I can get. One of my mistakes was I ended up building two different databases and tried to merge them into a third when I tried to make save/load functions. 

Creating one from the get-go as a separate entity might be able to stop me from doing that as well as help with load and save functions. Do you think RC1 is ready for that kind of test? It would also give me the opportunity to talk more about it in a future post.

**Comment by radubolovan** [comment]
2.0 RC1 is ready for testing and I already have a fix for the last bug that I found. I'll commit tonight after some code clean up.
I think I'll make a 2.0 Stable release in the next weekend and also upate the request for AssetsLib. But first I need to update the documentation a little bit.

About the future, I also have a plan:
- 2.1: fix major interface problems. I recently bought a 4K monitor and there are a lot of issues regardin interface. I really want to have the possibility to resize all the containers and the cells.

- 3.0:
1. Improve interface icons
2. Improve the database output: currently all the data is a huge array. I want to implement the output to be an array of JSONs as rows of data.
3. Add a possibility to set a default value to a property when adding new rows to a table.
4. Add more data types: https://docs.godotengine.org/en/3.1/getting_started/scripting/gdscript/gdscript_basics.html#basic-built-in-types

But to be honest I have no idea when I'll find the time to do all of these. In time I guess :)

If you have other ideas about improvements in your mind, please feel free to share.

Cheers!

**Comment by radubolovan** [comment]
What do you think about a few more features that I have in mind for 3.0?

1) In a table's structure, move the properties up/down
2) In a table's data, remove row of data
3) Duplicate table's structure: copy/paste only the structure into a new one named by the user
4) Duplicate table: the same as 3), but the data as well
5) Duplicate database's structure: copy/paste all the tables except data from them.
6) Duplicate database: the same as 5), but the data from the tables as well
7) Reload a database <- I think this is going to be usefull if a user edits a database from code, but it's already loaded into the interface.

**Comment by DCowboy** [comment]
Those could turn out really useful.

Also, I've refined my singleton idea that I suggested on Facebook when I was there. Perhaps when saving through the interface have an option that it could add/edit a singleton dictionary to the project as the database name? I still think doing something of that nature would help mesh the interface and the user's code together, and eliminate the need for the user to create another load function if they create the database through the interface. Plus, it might help with the reload a database feature as it could react to the singleton which would likely be the most up to date form of the database.

**Comment by DCowboy** [comment]
I was looking at db_interface.gd and comparing it to the save functions I was making myself to figure out how to make the most of it. I realize now that my suggestion above would require a fair bit of refactoring to keep it clean.

I don't have, well, any real collaborating experience, so, all I know for sure is that I don't want to step on your toes and piss you off. That said, I might be able to do a dirty rewrite of the save button function that could at least show you what I'm talking about if not actually end up helping a bit. Might you be interested if I did?

Edit: As what I'm talking about speaks your wanting to improve database output. I figured I'd show the difference in output of my save function vs your current output. Granted, my save function was basically one table it wouldn't be difficult for me to expand the concept for multiple tables, which would also make it not that difficult to expand again for sub-tables feature (not quite relational)
![differences_json](https://user-images.githubusercontent.com/4471773/83344115-bf069b80-a2d0-11ea-94d2-e9e340ec57ed.png)

For some reason it's not letting me upload the image. I'm trying to figure out what the issue is.

Edit 2: Apparently I was too stingy on my browser permissions...lol

**Comment by radubolovan** [comment]
About singleton, I think that they should be related to projects and users manage them manually. At least for now I don't find this a priority, but I'll think about it.

For instance, in my project I have a singletone called "g_globals". In this file I have a variable that points to an instance of an application class, and in the application class I have a member that points to a GDDBMan and a function that returns the database manager. And this is how I access it from code:
g_globals.get_app().get_db_manager().get_db_by_name("game_data")

Perhaps I should add more examples in the future, but for now I think it's very clear in the docs how to manage database manager and databases.

**Comment by DCowboy** [comment]
It is clear how to initiate and create a database to use with the tool, through code. But, what about when the user starts by creating a new database via the interface using the New DB button and then wants to hook their code to it? That's what I'm trying to help figure out a good way to address. Please understand that my intention is not to be critical, but honestly trying to help shorten the gap between using the interface and doing things by code, especially during database creation where the gap seems the most pronounced.

As best as I've been able to figure out, if you create a new database through the interface, (New DB button,) the user's project can only use it if they create or modify a copy the tool's load function to make it interact with their code even half as well as if they they had initiated it through code as you describe in the docs.

Maybe another way to go would be to create a variable dictionary inside the tool that could be accessed via code about the same way as creating the database through the code. Using a dictionary, or rather a dictionary(database[tables]) of dictionaries(table[properties]) of dictionaries(property:data) might help database output as well as you could iterate through the dictionaries using db_variable.store_line(to_json(line_variable))

I apologize if I'm being a bother. I truly am just excited to be collaborating and therefore trying to be all the help I can.

**Comment by radubolovan** [comment]
The same way.
When creating a database via "New DB" button, you need to give it a name and save it. After saving it, you can access it via code as I said in my previously comment.

And yes, if you want to access the database through code, you have to load it first.

Let me get this straight. You want to make a singleton that will automatically load the database in the _ready function? This is a bad idea, because if you will edit the database via interface, the singleton won't know how to refresh its content automatically unless you will reload the entire project.

If you want to access the database via code, you have to write code :)

**Comment by DCowboy** [comment]
Of course you have to write code to access it. It just seems like I'm doing something twice that I ordinarily wouldn't. Perhaps it's just the way I'm looking at the situation, like perhaps the difference between the way I normally do it vs the way the tool is set up to work perhaps?

With the singleton idea, I was thinking the save button would update the database the way I tend to update dictionaries whether I'm saving them to file or not. The way I've learned to do things without the tool, it gets tiresome keeping track of the structure sometimes. This tool seems like it could help with that, well, after I get my head around what it is I'm tripping over that is.

**Comment by radubolovan** [comment]
This is close to impossible for me.
But feel free to experiment if you like :)
In theory all you have to do is to call a function that will update the singleton when save the database via interface.
But if you edit the database within the interface when the game / project is running, you'll have a lot of headache to synchronize the data between the database and the running project.

**Comment by DCowboy** [comment]
I wasn't thinking about when the game was running at all. I thought the tool was only meant to help visualize structure, perhaps add initial values, Not to be used while the game was running. 

Since I'm prototyping, structure of my dictionaries, (essentially mini-databases,) tend to change while I'm figuring out stuff. I expected, that with the tool, I could change the structure via interface and add/change the code I had for it that is affects that part of the structure and still have the structure right there to see it visualizing it. I didn't expect to use the tool during runtime, Only the database it leaves behind. The only thing runtime would be able to change would be the data, not the structure. As in runtime, might add a row, or change a field. 

During testing, when runtime, changed the data, saved and ended, I would expect to hit load database again if I wanted to see the data.

**Comment by DCowboy** [comment]
Maybe that's it. perhaps the way I have been doing it is by basically hard-coding the database myself and have been looking at the tool the wrong way?

**Comment by radubolovan** [comment]
Perahps; I don't know.

This tool is made to manage (create and edit) databases that will help players to view data for their games. Right now each database is saved to a JSON. It's a WYSIWYG editor for JSON.

It's an alternative to Google Sheets that runs inside Godot Editor. Instead using Google Sheets, you use this tool inside Godot Editor. You export that JSON from the tool and use it in your project. The interface uses an API that can be used for other projects too. And that's pretty much all about it.

**Comment by DCowboy** [comment]
Sorry, it was getting really late for me last night. Sometime before I fell asleep, I realized what I was unintentionally asking for with the singleton idea was for the addon to also create/modify a .gd file, (Which in the end would mean it wouldn't even need to be a singleton.) While it would be possible, that realization helped me also realize it was out of your intended scope, even before reading your reply this morning.

As for your latest reply, it turns out that I was looking at it completely the wrong way. I was trying to use it as an integrated planning/organization helper for the developer, rather than as what I'm understanding you to be describing as a documentation/information tool for the player.

Your idea and interface has good potential for both. You wouldn't be offended if I refactored it to turn it into the developer tool i mistook it for, would you? If you wouldn't be, I'm terrible at naming things, What would a good new name be to differentiate it, yet still identify it as an adaptation of your work to pay homage to your effort?

**Comment by radubolovan** [comment]
Hey there,
Sorry for late reply. Very busy here.

No, I won't be offended in any way. But about the name, I have no idea. Free your mind :)

**Comment by radubolovan** [comment]
One feature I have in my mind that might help you:
A button in the menus called "Generate structures" (or something similar). And once you press that button, will create a directory in the project called "GDDB_structures" (or something similar).
And in that directory, the tool will create a ".gd" file for each database containing a class for each table in that database with the structure.

Here's an example with 1 database, 1 table, 3 properties:
Database: test_db
Tables: aaa
Properties: id(int), name(string), data(string)

gd file:
`
extends Node
class_name test_db

class DBaaaTable :
    var m_id : int = -1
    var m_name : string = ""
    var m_data : string = ""

var m_aaa_table : Node = null

func _ready() -> void :
    m_aaa_table = DBaaaTable.new()
    # fill here the table with the data from the database
`

Hm ... I think this is a very nice feature to have for 3.0. I need to design this properly.

**Comment by DCowboy** [comment]
That's generally what I was talking about. I think an easier way to go about it though would be to convert to dictionaries for this. That's what I've started playing with. 

So far, In the previous version, I changed the save button function to iterate through the arrays like you were doing to create your text file to instead fill a dictionary, (named database for convenience,) instead. Then when in write mode, I iterated through the dictionary using store_line( to_json(database[each]). before closing. As I just made the loop as simple as possible, it prints one table per line.

However, When I tried to apply that to RC2 in database.gd's save function, I apparently messed something up because it stopped saving and I went to bed at 2am my time without solving it. 

After I solve that and then get the load function to load it, my next planned step is to attempt a function to write a .gd file the same way you were writing the .json file. For the first form of it, I was just going to write "extends Node", a couple new lines, then "var " + database name  + " = { /n" and then iterate through the tables properties(keys) and data.  

Edit: Sorry, I'm drinking my first cup of coffee as I wrote and am now editing this, I just realized it would be easier to include my modified database.gd file so you can see what I'm talking about and maybe even see what I messed up trying to work on it late at night...lol It seems I need to change the file extension to .txt to be able to load it here. The parts I typed are obviously not in your style yet. I'm used to trying to write self-documenting code. I figured I'd try to match your style after I got it all working properly.


[database.txt](https://github.com/radubolovan/Godot-Database-Manager/files/4759192/database.txt)

**Comment by DCowboy** [comment]
I'm currently working on changing to the new function names as I find them. In doing so, I think I have more information about your bug. I'll post that info there.

Edit: I fixed the function names and have it saving again. Now I'm trying to get the loops right to record the data as it relates to the properties. After that, I guess I can go to the load function and start doing it backwards. since there's a check for a valid database, is there another function besides the load function that I'll have to take into account?

**Comment by radubolovan** [comment]
Right now I'm busy with my work and trying to release 2.1. After the 2.1, I'll think about that design of that feature.

If I find some time, I'll take a look at that file in the next weekend.

About that load database function, check the load_database function in the db_man.gd file.

**Comment by DCowboy** [comment]
I understand you're busy and still working on 2.1, and I'm in no real rush other than in my own efforts for my own sake. Hence, there are many reasons I'm going ahead with it:
It provides me a chance at being genuinely helpful.
It advances my interest.
It offers another suggestion on human readable output.
it could help with preliminary work on the future feature if you like it enough to incorporate into the plan.
It's giving me experience with your code base since I'm a kinesthetic learner.

That said, I have the save file working now and the only thing in its current form that *it's missing is the auto-increment value, which would be a simple matter to add if you like it.* Edit: Auto_increment, (and table_name,) has been added since I'll need it for the load function, plus, I noticed and fixed some errors in the formatting, but thought the changes too small to include the new files unless you're interested. I'm including it and  the test file with the output for it as well. I would rather you look at this version as it works with the current version as the first one only worked on version 1.0. Apparently .json files have to have their extension changed too.

EDIT 2: The load function was much easier to do than I thought, (after I got the save file to format correctly.) Since I have it saving and loading correctly I'll update these files so you can look at both functions if you wish. Neither function is currently fully in your naming convention yet, but it should be good enough to get the idea across.

I'll hold off now and wait for your reply, but, I think I have a fairly clear idea on a way to create a function to write .gd file based of what I have done. I think I could also easily add it to options if you want to see what that would look like.

[database.txt](https://github.com/radubolovan/Godot-Database-Manager/files/4773843/database.txt)
[test_31.txt](https://github.com/radubolovan/Godot-Database-Manager/files/4773844/test_31.txt)

**Comment by radubolovan** [comment]
Hey there,

Looks like I find less and less time for this :(
Too busy with my job and other projects. So sorry, but I simply have no idea when I'll continue to work on this :/

Cheers,
Radu
