### ISSUE TITLE
[BUG][2.1] After canceling the edit_table_dlg, adding a new table results in editing the current table.

### ISSUE THREAD

**Issue by radubolovan** [radubolovan/Godot-Database-Manager#22]
Steps to reproduce:

1. Create a new database
2. Create a table
3. Press the "edit table button" and cancel the "edit table dialog"
4. Create a new table
5. Observe that the current table's name is modified instead of adding a new table

**Comment by DCowboy** [comment]
This might be related. While I was playing with db_interface.gd, I saved and re-opened the tool the information on the interface was still there but m_tables.size() returns to 0.

**Comment by DCowboy** [comment]
Edit:Nevermind. I was doing something stupid.

This also seems to happen every time you close the interface window. It appears that every time the interface window or popup is canceled it reverts the back end to default while everything displayed remains. In addition, if you try create a new database you will get the "already exists" error, even if it does not.
This is just a suggestion, but what I would try would be to auto-save automatically (remove the option) and load the last database opened every time the interface window is on top. Perhaps, instead allow for the possibility to clear data fields and delete data rows?

You probably have a better solution though.

**Comment by radubolovan** [comment]
Thanks for your catch, but your case might be similar, but it's a different issue.
I'll try to reproduce it and find a fix. Please don't erase your comment so I can fix that too.

I already found what is the problem with the original issue: I'm using the same dialog for "add_new_table" and for "edit_table", but in some cases the signal doesn't get disconnected and a different function is called.
I'm working for a fix for this one.

**Comment by radubolovan** [comment]
Looks like I can't reproduce your issue after my fix. They must have been related after all.
I'm closing this.

If you still reproduce it, please create an new issue with repo steps. If you find more than one bug, please make separated issues for each one (even if they are related) and I'll take it from there.

Also please make sure you checkout the 2.1 branch before testing.
