### ISSUE TITLE
[IMPROVEMENT] Hard to understand documentation. I can help

### ISSUE THREAD

**Issue by bodamat** [radubolovan/Godot-Database-Manager#24]
I love your plugin. I wanted to do the same :) 
But I didn't understand how to get data from the table. Documentation is hard to me and function has a lot of short names. I think is bad to read and understand.
I don't like popup window, because need always finds it in a menu and can't edit the table and write at the same time. I think need to switch to the tab like tab "script". Easy to switch and don't need to find the tool in the menu often.

**Comment by radubolovan** [comment]
I merged the 2.1 branch into master.
Check the documentation again please.

**Comment by bodamat** [comment]
Thanks a lot. It much better. Sorry I didn't help you :(
Could you explain, please, what 'm_' in m_db_man mean?

**Comment by radubolovan** [comment]
It doesn't mean anything.
I'm just used to "m_" all properties of a class in C++ and I'm doing it in GDscript too.
Old habbits die hard :)

**Comment by bodamat** [comment]
So we can close this issue?

**Comment by radubolovan** [comment]
Closing the issue.
