### ISSUE TITLE
[BUG] [2.0] No menu reaction - "gddb_constants" isn't declared

### ISSUE THREAD

**Issue by Arkadeievitch** [radubolovan/Godot-Database-Manager#25]
Hello
I tried to use this add-on. I can dowload and install it as described in documentation.

When I enable it in Project Settings, Godot returns the following issues:
```
 res://addons/godot_db_manager/db_interface.gd:15 - Parse Error: The identifier "gddb_constants" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR

 res://addons/godot_db_manager/dlgs/new_db_dlg.gd:30 - Parse Error: The identifier "gddb_globals" isn't declared in the current scope.
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
```

However, I can start it in Project>Tools and the main window appears. After this point, the commands in File>New DB/Load DB don't answer.

OS : Windows10
Godot 3.2.2.stable

The error occured for downloads from the Godot Engine and Github.
I committed the folder as well as a few screenshots here : https://github.com/Arkadeievitch/DataBaseManager_Issue/tree/master

Thanks for reading.

**Comment by radubolovan** [comment]
Hello,

Please make sure you enable the plugin in the Project settings:
From menu:
"Project" -> "Project Settings" -> "Plugins" tab -> check the status.
The checkbox should be enabled.

**Comment by EntropiaFox** [comment]
> Hello
> I tried to use this add-on. I can dowload and install it as described in documentation.
> 
> When I enable it in Project Settings, Godot returns the following issues:
> 
> ```
>  res://addons/godot_db_manager/db_interface.gd:15 - Parse Error: The identifier "gddb_constants" isn't declared in the current scope.
>  modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
> 
>  res://addons/godot_db_manager/dlgs/new_db_dlg.gd:30 - Parse Error: The identifier "gddb_globals" isn't declared in the current scope.
>  modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR
> ```
> 
> However, I can start it in Project>Tools and the main window appears. After this point, the commands in File>New DB/Load DB don't answer.
> 
> OS : Windows10
> Godot 3.2.2.stable
> 
> The error occured for downloads from the Godot Engine and Github.
> I committed the folder as well as a few screenshots here : https://github.com/Arkadeievitch/DataBaseManager_Issue/tree/master
> 
> Thanks for reading.

Hello! I know it's been quite a while since you posted this and I have to find the _actual_ reason as to why that error is happening, but the issue seems to be related to gddb_constants/gddb_globals being tried to be accessed before the interface enters the tree and so before they can be declared as singletons, so adding this line:

`var gddb_constants = load("res://addons/godot_db_manager/core/GDDBConstants.gd").new()`

Right at the beginning of `db_interface.gd` seems to mitigate it. Interestingly enough, once the plugin is loaded into a project, you can remove the line and it seems to work just fine. I'm probably going to be forking this project soon and I'll be adding the fix, plus a few more changes to better adapt to my own needs.

**Comment by Arkadeievitch** [comment]
Hi,

Thank you for taking it into account. 
As I currently don't use Godot (no projects on the table), I'm not going to test it directly. 
Although, you can tell me when you need me to try it (once your release is online, I guess), so I can close the issue. 

Thanks again!

**Comment by radubolovan** [comment]
Hello,

Thank you for your feedback.
I just merged 2.1 branch into master. Please pull and let me know if this still occurs.

I will update the addon on Godot Assets Lib soon.

**Comment by radubolovan** [comment]
I'm closing this.
No update.

**Comment by Arkadeievitch** [comment]
Hi, 

Sorry for the delay and thank you for your replies. 
I tried a few times with former and current godot release (3.3), but the error remains the same (gddb_constant error during installation and no answer when trying to create a new DB). DBM version is 2.1.a.

However, as I said earlier, it's quite unlikely that I use godot soon, so if I'm the lonely one to get this error, it's probably not worth wasting your time on it (probably some godot config error or something like that),

Thanks again and have a good day!
