### ISSUE TITLE
[BUG] Data adding without a property and limited rows

### ISSUE THREAD

**Issue by nonunknown** [radubolovan/Godot-Database-Manager#4]
* When the users add a property A, then delete it the user still can add properties.
* Maybe implementing a vscroll to Properties and Data could solve the problem too

![database](https://user-images.githubusercontent.com/58845030/75629550-bdd6ad00-5bc1-11ea-8ed1-33b3610c2fb9.gif)

**Comment by radubolovan** [comment]
Good catch!
This should be fixed with commit e1016356985131c980aea4d1cdcfb635ec9c41cd into master branch.

If you have the time and will, please fetch/pull and test again.
Thank you!

**Comment by radubolovan** [comment]
I'm closing this. If the issue persists, I'll reopen.
